# Generated by Django 3.0.6 on 2020-05-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investororganization',
            name='address',
            field=models.TextField(),
        ),
    ]
