# Generated by Django 3.0.6 on 2020-05-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0010_auto_20200526_1504'),
        ('investor_management', '0002_auto_20200525_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorOrgSMEProjectInvestments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investor_org', models.ManyToManyField(to='investor_management.InvestorOrganization')),
                ('sme_project', models.ManyToManyField(to='sme_management.SMEProject')),
            ],
        ),
    ]
