# Generated by Django 3.0.6 on 2020-05-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('address', models.TextField(default='No Address Present')),
                ('documents', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='SMEProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='No Project Name Given', max_length=255)),
                ('business_plan', models.TextField()),
                ('tenure', models.DateField()),
                ('documents', models.FileField(upload_to='projects/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SMEUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sme_management.SME')),
            ],
        ),
    ]
