# Generated by Django 3.0.6 on 2020-05-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0003_auto_20200523_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='documents',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
