# Generated by Django 3.0.6 on 2020-05-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0004_auto_20200523_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='documents',
            field=models.FileField(blank=True, default='EMPTY', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
