# Generated by Django 3.0.6 on 2020-05-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0007_auto_20200525_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='address',
            field=models.TextField(),
        ),
    ]
