# Generated by Django 3.0.6 on 2020-05-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0008_auto_20200525_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smeproject',
            name='documents',
            field=models.FileField(blank=True, upload_to='projects/'),
        ),
    ]
