# Generated by Django 3.0.6 on 2020-05-26 15:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0009_auto_20200525_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smeproject',
            old_name='tenure',
            new_name='investment_tenure_end_date',
        ),
        migrations.AddField(
            model_name='smeproject',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='smeproject',
            name='amount_required',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='smeproject',
            name='equity_offering',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='smeproject',
            name='project_completion_status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('UNAPPROVED', 'UNAPPROVED')], default='UNAPPROVED', max_length=255),
        ),
        migrations.AlterField(
            model_name='smeproject',
            name='project_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('amount_required', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sme_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sme_management.SMEProject')),
            ],
        ),
    ]
