# Generated by Django 3.0.6 on 2020-05-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0010_auto_20200526_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Milestones',
            new_name='SMEProjectMilestones',
        ),
    ]
