# Generated by Django 3.0.6 on 2020-05-29 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0011_auto_20200527_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smeproject',
            name='documents',
        ),
        migrations.AddField(
            model_name='smeproject',
            name='financial_docs',
            field=models.FileField(default=None, null=True, upload_to='financial-docs/'),
        ),
        migrations.AddField(
            model_name='smeproject',
            name='project_description',
            field=models.TextField(default='NO DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='smeproject',
            name='sme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sme_management.SME'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smeproject',
            name='business_plan',
            field=models.FileField(default=None, upload_to='business-plans/'),
        ),
    ]
