# Generated by Django 3.0.6 on 2020-05-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0012_auto_20200529_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smeproject',
            name='financial_docs',
        ),
        migrations.AddField(
            model_name='smeproject',
            name='balance_sheet',
            field=models.FileField(default=None, null=True, upload_to='balance-sheets/'),
        ),
        migrations.AddField(
            model_name='smeproject',
            name='cashflow_statement',
            field=models.FileField(default=None, null=True, upload_to='cashflow-stmts/'),
        ),
        migrations.AddField(
            model_name='smeproject',
            name='income_statement',
            field=models.FileField(default=None, null=True, upload_to='income-stmts/'),
        ),
    ]
