# Generated by Django 3.0.6 on 2020-05-31 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0013_auto_20200531_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smeprojectmilestones',
            name='sme_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones_project', to='sme_management.SMEProject'),
        ),
    ]
