# Generated by Django 3.0.6 on 2020-05-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0014_auto_20200531_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeprojectmilestones',
            name='proof_of_completion',
            field=models.FileField(default=None, null=True, upload_to='milestone-complete-proof/'),
        ),
    ]
