# Generated by Django 3.0.6 on 2020-05-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0015_smeprojectmilestones_proof_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeprojectmilestones',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('NOT_STARTED', 'NOT_STARTED')], default='NOT_STARTED', max_length=255),
        ),
    ]
