# Generated by Django 3.0.6 on 2020-06-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0016_smeprojectmilestones_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeprojectmilestones',
            name='sme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sme_management.SME'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smeprojectmilestones',
            name='sme_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sme_management.SMEProject'),
        ),
    ]
