# Generated by Django 3.0.6 on 2020-06-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0017_auto_20200601_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smeproject',
            old_name='project_completion_status',
            new_name='status',
        ),
    ]
