# Generated by Django 3.0.6 on 2020-06-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0018_auto_20200601_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smeprojectmilestones',
            name='sme',
        ),
    ]
