# Generated by Django 3.0.6 on 2020-06-03 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sme_management', '0019_remove_smeprojectmilestones_sme'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeprojectmilestones',
            name='sme',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='sme_management.SME'),
            preserve_default=False,
        ),
    ]
