# Generated by Django 3.0.6 on 2020-05-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255, verbose_name='Sender Name')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Recipient Name')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
                ('transaction_type', models.CharField(choices=[('DISBURSEMENT', 'DISBURSEMENT'), ('INVESTMENT', 'INVESTMENT')], default='OTHER', max_length=255)),
            ],
        ),
    ]
